### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by rgiuli** [PredixDev/timeseries-bootstrap#3]
`git clone https://github.com/PredixDev/winddata-timeseries-service.git`
`cd winddata-timeseries-service/`
`mvn -U clean package`

I get this error:
````
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.763 s
[INFO] Finished at: 2016-08-24T10:39:26-07:00
[INFO] Final Memory: 16M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project winddata-timeseries-service: Could not resolve dependencies for project com.ge.predix.solsvc:winddata-timeseries-service:jar:2.0.1: The following artifacts could not be resolved: com.ge.predix:uaa-token-lib:jar:2.0.0, com.ge.predix:acs-spring-security-extensions:jar:5.1.0, com.ge.predix.solsvc:ext-model:jar:2.0.1, com.ge.predix.solsvc:timeseries-bootstrap:jar:2.0.1: Could not find artifact com.ge.predix:uaa-token-lib:jar:2.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
````

I'm following the instructions at:
https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=1553&tag=1605&journey=Build%20a%20basic%20application&resources=1580,1569,1523,1544,1547,1549,1556,1553,1570

I can get timeseries-bootstrap, but I don't know where the other repositories are (tried finding them here). Anyways, considering the other tutorials work, this one should also. Thanks!

**Comment by rgiuli** [comment]
Update: this fixed it:
````
git clone https://github.com/PredixDev/ext-interface
cd ext-interface
mvn install
cd ..
https://github.com/PredixDev/predix-rest-client
cd predix-rest-client
mvn -DskipTests=true install <== This had test build failures, so I skipped tests
cd ..
git clone https://github.com/PredixDev/predix-websocket-client
cd predix-websocket-client
mvn -DskipTests=true install <== <<< FAILURE! - in com.ge.predix.solsvc.websocket.client.WebSocketClientIT
cd ..
git clone https://github.com/PredixDev/timeseries-bootstrap
cd timeseries-bootstrap
mvn -DskipTests=true install
<== Tests in error:  runIDataInjectionTest(com.ge.predix.solsvc.timeseries.bootstrap.factories.TimeseriesFactoryIT): unable to call url=https://5f37babc-08cd-4d3c-9f7f-0ffd3b474f0f.predix-uaa-sysint.grc-apps.svc.ice.ge.com/oauth/token
cd ../cd winddata-timeseries-service
+ Edited pom.xml and changed uaa-token-lib.version to 3.1.5
+ Removed the dependency "acs-spring-security-extensions"
mvn -U clean package
````

It now builds. In summary:
1. I pulled and installed the repositories locally, and several of them do not compile unless skipping tests
2. I couldn't find aaa-token-lib but there is an online version (3.1.5)
3. I had to remove the dependency "acs-spring-security-extensions" because I can't find it anywhere

I'm not hopeful this will run since I had to remove  dependency and tests fail.

**Comment by rgiuli** [comment]
This was resolved by fixing artifactory, then you don't need to download all the repositories and build....

**Comment by turnerth** [comment]
per our convo, you needed to add your encrypted predix.io password to the ~/.m2/settings.xml

**Comment by rgiuli** [comment]
Yes, that worked.
