### ISSUE TITLE
Unable to resolve dependencies (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)

### ISSUE THREAD

**Issue by evgeny-grushko** [PredixDev/timeseries-bootstrap#4]
Hello when i try to execute "mvn clean package" i got error:

D:\temp>cd timeseries-bootstrap

D:\temp\timeseries-bootstrap>mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building timeseries-bootstrap 2.1.0
[INFO] ------------------------------------------------------------------------
Downloading: https://artifactory.predix.io/artifactory/PREDIX-EXT/com/ge/predix/solsvc/ext-model/2.0.2/ext-model-2.0.2.pom
Downloading: https://artifactory.predix.io/artifactory/PREDIX-EXT/com/ge/predix/solsvc/ext-model/2.0.2/ext-model-2.0.2.pom
Downloading: https://artifactory.predix.io/artifactory/PREDIX-EXT/com/ge/predix/solsvc/ext-util/2.0.2/ext-util-2.0.2.pom
Downloading: https://artifactory.predix.io/artifactory/PREDIX-EXT/com/ge/predix/solsvc/ext-util/2.0.2/ext-util-2.0.2.pom
Downloading: https://artifactory.predix.io/artifactory/PREDIX-EXT/com/ge/predix/solsvc/predix-rest-client/2.0.2/predix-rest-client-2.0.2.pom
Downloading: https://artifactory.predix.io/artifactory/PREDIX-EXT/com/ge/predix/solsvc/predix-rest-client/2.0.2/predix-rest-client-2.0.2.pom
Downloading: https://artifactory.predix.io/artifactory/PREDIX-EXT/com/ge/predix/solsvc/predix-websocket-client/2.1.0/predix-websocket-client-2.1.0.pom
Downloading: https://artifactory.predix.io/artifactory/PREDIX-EXT/com/ge/predix/solsvc/predix-websocket-client/2.1.0/predix-websocket-client-2.1.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.798 s
[INFO] Finished at: 2016-09-16T15:59:11+03:00
[INFO] Final Memory: 15M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project timeseries-bootstrap: Could not resolve dependencies for project com.ge.predix.solsvc:timeseries-bootstrap:jar:2.1.0: Failed to collect dependencies at com.ge.predix.solsvc:ext-model:jar:2.0.2: Failed to read artifact descriptor for com.ge.predix.solsvc:ext-model:jar:2.0.2: Could not transfer artifact com.ge.predix.solsvc:ext-model:pom:2.0.2 from/to predix.repo (https://artifactory.predix.io/artifactory/PREDIX-EXT): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

D:\temp\timeseries-bootstrap>

**Comment by turnerth** [comment]
Hi, you need to add your predix.io username and password to your maven settings.xml because the artifactory is password protected.  In the Guides you'll find several tutorials which link to the maven setup tutorial explaining this.
