### ISSUE TITLE
Issue in building the project

### ISSUE THREAD

**Issue by soumya-github** [PredixDev/timeseries-bootstrap#6]
I am using Spring Tool Suite in my windows laptop(not using the Predix Devbox) to build the project. I am getting the below error while trying to build the project.
 Downloading: http://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-parent/1.2.3.RELEASE/spring-boot-starter-parent-1.2.3.RELEASE.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.ge.predix.solsvc:timeseries-bootstrap:2.1.11: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:1.2.3.RELEASE from/to predix.repo (https://artifactory.predix.io/artifactory/PREDIX-EXT): connect timed out and 'parent.relativePath' points at no local POM @ line 44, column 10

**Comment by turnerth** [comment]
please see the forum for answer.

**Comment by elluck91** [comment]
What forum?

**Comment by turnerth** [comment]
The person who originally posted asked the exact same question in the Predix Forum.  You can search by their username to find the post.

https://forum.predix.io
