### ISSUE TITLE
cannot build maven project

### ISSUE THREAD

**Issue by vivekagarwal5592** [PredixDev/timeseries-bootstrap#7]
Failed to execute goal on project winddata-timeseries-service: Could not resolve dependencies for project com.ge.predix.solsvc:winddata-timeseries-service:jar:2.0.37: Failure to find com.ge.predix.solsvc:timeseries-bootstrap:jar:2.1.34 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

**Comment by turnerth** [comment]
Fixed.  Used our new build process which avoids human mistake on forgetting to click one of the jenkins steps.  Sorry about that.  Please do a git pull on winddata and a mvn clean package.
